### ISSUE TITLE
In iOS it's not working

### ISSUE THREAD

**Issue by rakib32** [MrSwitch/hellojs-phonegap-demo#11]
Here is my code:
           var options = {scope: "email"};
             var facebook = hello('facebook');

            facebook.login(options).then(function () {
                console.log("login FB"); //callback is not executing after clicking on done
                facebook.api('me').then(thisControl.fbLoginHandler, thisControl.errorHandler);
            });

**Comment by MrSwitch** [comment]
wont fix
