### ISSUE TITLE
Redirect URI

### ISSUE THREAD

**Issue by kegita** [MrSwitch/hellojs-phonegap-demo#5]
if I want to implement Facebook login with my app, can you please define which steps and, above all, which redirect url i have o define?? Because i have tried to change redirect uri but i have had no success Thanks

**Comment by raibutera** [comment]
@kegita I'd recommend reading through Jakob Jenkov's [OAuth 2.0 Tutorial](http://tutorials.jenkov.com/oauth2/index.html) as it will help clear up OAuth and redirect urls

**Comment by MrSwitch** [comment]
The redirect_uri just needs to be the one you registered with Facebook as a web application.

**Comment by kegita** [comment]
I have read a lot of tutorial (also on Facebook) and is written that i have to insert 
1) Valid OAuth redirect URIs . The Facebook guide says to use https://www.facebook.com/connect/login_success.html
2) Replicate this url on hello.init

I have tried this process but login doesn't start. Which is the problem?

**Comment by MrSwitch** [comment]
inactive
