### ISSUE TITLE
ios redirect page doesn't close

### ISSUE THREAD

**Issue by Ascendzor** [MrSwitch/hellojs-phonegap-demo#7]
Hi there

I'm on ios and using facebook for hellojs.
I can auth properly but it opens my redirect page and never closes it, essentially losing access to the rest of the app.

Any thoughts on why this is happening?

**Comment by ITGoneWild** [comment]
Same here. Ionic with inappbrowser, works fine on Android but on iOS i get stuck on the redirect page.

**Comment by MrSwitch** [comment]
inactive

**Comment by rockneverdies55** [comment]
The app gets stuck on the redirect page (tested on android emulator).

Is that expected?

User has to close that page and continue?
