### ISSUE TITLE
using plugin for instagram

### ISSUE THREAD

**Issue by cordova-android** [MrSwitch/hellojs-phonegap-demo#8]
after doing all requirements
 i get error in Xcode out put says 
failed to load webpage with error :the operation couldn't be completed

**Comment by MrSwitch** [comment]
How is this related to instagram? What are the steps to reproduce this?

**Comment by cordova-android** [comment]
i download demo project and i set inapp browser plugin and in page index html i click instgram button to login user 
like:
 <button onclick="hello('instagram').login(loginHandler)">instagram</button>

 <script>

            // Initate the library
            hello.init({
                instagram : 'ClientID'
            }, {
                //
                // Define the OAuth2 return URL
                // This can be anything you like, providing its the callback which you have registered with the providers for OAuth2
                // It could even be localhost, e.g. http://localhost/somepath as phonegap is not run from a domain so SameOrigin breaks, instead we take advantage of being able to read the popups URL in PhoneGap
                redirect_uri : 'http://adodson.com/hello.js/redirect.html'
            });

            function loginHandler(r){
                log(r);
                hello(r.network).api('me').on('complete', log);
            }

            function log(r){
                var s = document.createTextNode(JSON.stringify(r, null, "\t"));
                var pre = document.getElementsByTagName('pre')[0];
                pre.insertBefore(s, pre.firstChild);
            }
        </script>

i log in in emulator but it do redirect to my page again 
![and](https://cloud.githubusercontent.com/assets/11616292/12417399/8a190416-beb0-11e5-9513-fcfef5213d2d.png)

**Comment by MrSwitch** [comment]
That seems a bit weird. In the browser window you have what looks to be my redirect page http://adodson.com/hello.js/redirect.html yet the address bar is saying its on https://instagram.com/...

**Comment by cordova-android** [comment]
i set redirect url http://adodson.com/hello.js/redirect.html 
and in Instagram too

**Comment by MrSwitch** [comment]
indeed

**Comment by cordova-android** [comment]
you checked this in your emulator?

**Comment by MrSwitch** [comment]
Nope, i dont have it set up. Also i asked you why your emulator shows the page http://adodson.com/hello.js/redirect.html yet the address bar is saying https://instagram.com/... is that a glitch in your emulator?

**Comment by MrSwitch** [comment]
I.e. Is it stuck on a network request? Check your emulator can access the internet.

**Comment by cordova-android** [comment]
i tried in real android device connected with internet but  the same problem still

**Comment by cordova-android** [comment]
Note: this case not occur in IOS only in android

**Comment by MrSwitch** [comment]
What's your android emulator version? Works for me in 5.1.

![screen shot 2016-01-20 at 12 37 36 pm](https://cloud.githubusercontent.com/assets/947163/12449128/f9125d00-bf72-11e5-9a37-ea8b43be8743.png)

**Comment by cordova-android** [comment]
i tried in real android device connected to wifi but it still have problem

**Comment by cordova-android** [comment]
i attachedv my cordova app in zip file can you run it in your emulator
in this link
http://www.filedropper.com/demo_10

**Comment by cordova-android** [comment]
i added you in my sandbox Instagram with your name:mrswitch

**Comment by cordova-android** [comment]
i will wait you for this problem if it will appear to you too

**Comment by cordova-android** [comment]
my android emulator version is 5.1 too

**Comment by MrSwitch** [comment]
@cordova-android i've rebuilt my project and this bug has appeared in there too, so i can now recreate it.

I've tracked an issue to InAppBrowsers "loadstart" not being fired. I'm trying to find out more about the issue which seems to be a common problem https://groups.google.com/forum/#!topic/phonegap/e5_5unC2fYs

However i've yet to understand why this is occuring or how to prevent it.

**Comment by MrSwitch** [comment]
I think this is the issue we're seeing https://issues.apache.org/jira/browse/CB-10407

**Comment by cordova-android** [comment]
is there an other plugin act as InAppBrowser plugin?

**Comment by cordova-android** [comment]
is there changes or updates will be done for this issue

**Comment by MrSwitch** [comment]
As per this comment https://issues.apache.org/jira/browse/CB-10407?focusedCommentId=15121027&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15121027

You can install the fix from the github repo
